const S={user:null,role:null,lang:"kh",products:[],category:"All",cart:{},currency:"KHR",payment:"Cash",rate:Number(localStorage.getItem("nm_rate")||4000),sales:JSON.parse(localStorage.getItem("nm_sales_v4")||"[]")};
const $=id=>document.getElementById(id); function moneyKHR(n){return Number(n||0).toLocaleString()+"៛"} function moneyUSD(n){return "$"+Number(n||0).toFixed(2)}
async function boot(){S.products=await fetch("products.json").then(r=>r.json());$("loginBtn").onclick=login;$("password").addEventListener("keydown",e=>e.key==="Enter"&&login());$("logoutBtn").onclick=()=>location.reload();$("langBtn").onclick=toggleLang;$("menuSearch").oninput=renderProducts;$("rateInput").oninput=e=>{S.rate=Math.max(1,Number(e.target.value||4000));localStorage.setItem("nm_rate",S.rate);renderCart();refreshAll()};document.querySelectorAll(".tab").forEach(b=>b.onclick=()=>showPage(b.dataset.page,b));document.querySelectorAll(".currency-btn").forEach(b=>b.onclick=()=>{S.currency=b.dataset.currency;document.querySelectorAll(".currency-btn").forEach(x=>x.classList.toggle("active",x===b));renderCart()});document.querySelectorAll(".pay-btn").forEach(b=>b.onclick=()=>{S.payment=b.dataset.payment;document.querySelectorAll(".pay-btn").forEach(x=>x.classList.toggle("active",x===b))});$("saveSaleBtn").onclick=saveSale;$("exportPng").onclick=exportPng;$("copyText").onclick=copyText;$("downloadTxt").onclick=downloadTxt;$("shareTelegram").onclick=shareTelegram;$("rateInput").value=S.rate;renderCategories();renderProducts();refreshAll()}
function login(){const u=$("username").value.trim(),p=$("password").value;if((u==="admin"&&p==="admin")||(u.startsWith("staff")&&p==="1234")){S.user=u;S.role=u==="admin"?"admin":"staff";$("loginScreen").classList.add("hidden");$("app").classList.remove("hidden");$("userLine").textContent=`${u} · ${S.role.toUpperCase()}`;if(S.role==="admin")$("adminTab").classList.remove("hidden");refreshAll()}else alert("Invalid username or password / ឈ្មោះអ្នកប្រើ ឬពាក្យសម្ងាត់មិនត្រឹមត្រូវ")}
function toggleLang(){S.lang=S.lang==="kh"?"en":"kh";renderCategories();renderProducts();renderCart();renderReport()}
function showPage(name,btn){document.querySelectorAll(".page").forEach(x=>x.classList.add("hidden"));$(name+"Page").classList.remove("hidden");document.querySelectorAll(".tab").forEach(x=>x.classList.remove("active"));btn.classList.add("active");if(name==="summary")renderReport();if(name==="history")renderHistory();if(name==="admin")refreshAdmin()}
function renderCategories(){const cats=["All","Coffee","Matcha","Cacao","Tea","Soda"],kh={All:"ទាំងអស់",Coffee:"កាហ្វេ",Matcha:"Matcha",Cacao:"កាកាវ",Tea:"តែ",Soda:"សូដា"};$("categoryBar").innerHTML=cats.map(c=>`<button class="chip ${S.category===c?"active":""}" onclick="setCategory('${c}')">${S.lang==="kh"?kh[c]:c}</button>`).join("")}
function setCategory(c){S.category=c;renderCategories();renderProducts()}
function renderProducts(){const q=($("menuSearch")?.value||"").toLowerCase();const list=S.products.filter(p=>(S.category==="All"||p[3]===S.category)&&(`${p[0]} ${p[1]}`).toLowerCase().includes(q));$("productGrid").innerHTML=list.map(p=>{const i=S.products.indexOf(p);return `<button class="product" onclick="addToCart(${i})"><div>${p[0]}</div><span class="kh">${p[1]}</span><span class="price">${moneyKHR(p[2])} / ${moneyUSD(p[2]/S.rate)}</span></button>`}).join("")}
function addToCart(i){const p=S.products[i];S.cart[i]=S.cart[i]||{name:p[0],kh:p[1],priceKHR:p[2],qty:0};S.cart[i].qty++;renderCart()}
function minus(i){if(!S.cart[i])return;S.cart[i].qty--;if(S.cart[i].qty<=0)delete S.cart[i];renderCart()}
function currentTotalKHR(){return Object.values(S.cart).reduce((s,v)=>s+v.priceKHR*v.qty,0)}
function renderCart(){const items=Object.entries(S.cart),totalKHR=currentTotalKHR();if(!items.length){$("cart").innerHTML='<div class="cart-empty">Select drinks / ជ្រើសភេសជ្ជៈ</div>';$("cartTotal").textContent="0៛";return}let rows="";for(const[i,v]of items){rows+=`<tr><td>${S.lang==="kh"?v.kh:v.name}</td><td><button class="qty-btn" onclick="minus(${i})">−</button> ${v.qty} <button class="qty-btn" onclick="addToCart(${i})">+</button></td><td>${S.currency==="KHR"?moneyKHR(v.priceKHR*v.qty):moneyUSD((v.priceKHR*v.qty)/S.rate)}</td></tr>`}$("cart").innerHTML=`<table class="cart-table"><tr><th>Item</th><th>Qty</th><th>Total</th></tr>${rows}</table>`;$("cartTotal").textContent=S.currency==="KHR"?moneyKHR(totalKHR):moneyUSD(totalKHR/S.rate)}
function saveSale(){const items=Object.values(S.cart);if(!items.length)return alert("Select a drink first / សូមជ្រើសភេសជ្ជៈ");const totalKHR=currentTotalKHR(),cups=items.reduce((s,v)=>s+v.qty,0),amount=S.currency==="KHR"?totalKHR:totalKHR/S.rate;S.sales.push({id:String(Date.now()),date:new Date().toISOString().slice(0,10),time:new Date().toLocaleTimeString(),user:S.user,payment:S.payment,currency:S.currency,amount,totalKHR,cups,rate:S.rate,items:items.map(v=>({name:v.name,kh:v.kh,priceKHR:v.priceKHR,qty:v.qty}))});localStorage.setItem("nm_sales_v4",JSON.stringify(S.sales));S.cart={};renderCart();refreshAll();renderReport()}
function today(){return new Date().toISOString().slice(0,10)}
function todaySales(){return S.sales.filter(s=>s.date===today())}
function summarize(){const out={khr:0,usd:0,khrCash:0,khrAba:0,khrOther:0,usdCash:0,usdAba:0,usdOther:0,cups:0,tx:0,items:{}};todaySales().forEach(s=>{out.cups+=s.cups;out.tx++;if(s.currency==="KHR"){out.khr+=s.amount;if(s.payment==="Cash")out.khrCash+=s.amount;else if(s.payment==="ABA")out.khrAba+=s.amount;else out.khrOther+=s.amount}else{out.usd+=s.amount;if(s.payment==="Cash")out.usdCash+=s.amount;else if(s.payment==="ABA")out.usdAba+=s.amount;else out.usdOther+=s.amount} s.items.forEach(i=>out.items[i.name]=(out.items[i.name]||0)+i.qty)});return out}
function refreshAll(){const x=summarize();$("kpiKhr").textContent=moneyKHR(x.khr);$("kpiUsd").textContent=moneyUSD(x.usd);$("kpiCups").textContent=x.cups;const mixed=x.usd+x.khr/S.rate;$("kpiMixed").textContent=moneyUSD(mixed);if(S.role==="admin")refreshAdmin()}
function refreshAdmin(){const x=summarize();$("adminKhr").textContent=moneyKHR(x.khr);$("adminUsd").textContent=moneyUSD(x.usd);$("adminCups").textContent=x.cups;$("adminTx").textContent=x.tx;$("adminKpi").textContent=moneyUSD(x.usd+x.khr/S.rate);$("adminRate").textContent=Number(S.rate).toLocaleString();const best=Object.entries(x.items).sort((a,b)=>b[1]-a[1])[0];$("bestSeller").textContent=best?`Best Seller / លក់ដាច់ជាងគេ: ${best[0]} · ${best[1]} cups`:"No sales yet / មិនទាន់មានការលក់";$("adminBar").style.width=Math.min(100,x.cups)+"%"}
function reportText(){const x=summarize(),d=new Date().toLocaleDateString("en-GB");let lines=[];lines.push("NONA-ME COFFEE");lines.push("DAILY SALES REPORT / របាយការណ៍ការលក់ប្រចាំថ្ងៃ");lines.push("Date: "+d);lines.push("");lines.push("KHR SALES: "+moneyKHR(x.khr));lines.push("USD SALES: "+moneyUSD(x.usd));lines.push("TOTAL CUPS: "+x.cups);lines.push("");lines.push("PAYMENT — KHR");lines.push("Cash: "+moneyKHR(x.khrCash));lines.push("ABA: "+moneyKHR(x.khrAba));lines.push("Other: "+moneyKHR(x.khrOther));lines.push("");lines.push("PAYMENT — USD");lines.push("Cash: "+moneyUSD(x.usdCash));lines.push("ABA: "+moneyUSD(x.usdAba));lines.push("Other: "+moneyUSD(x.usdOther));lines.push("");lines.push("MIXED TOTAL ≈ "+moneyUSD(x.usd+x.khr/S.rate)+" (rate "+Number(S.rate).toLocaleString()+"៛/$1)");lines.push("STAFF: "+(S.user||"—"));return lines.join("\n")}
function renderReport(){const x=summarize();$("summaryDate").textContent=new Date().toLocaleDateString("en-GB");const lines=[["KHR Sales / លក់ជារៀល",moneyKHR(x.khr)],["USD Sales / លក់ជាដុល្លារ",moneyUSD(x.usd)],["Total Cups / កែវសរុប",x.cups.toLocaleString()],["KHR Cash",moneyKHR(x.khrCash)],["KHR ABA",moneyKHR(x.khrAba)],["USD Cash",moneyUSD(x.usdCash)],["USD ABA",moneyUSD(x.usdAba)],["Mixed Total (approx.)",moneyUSD(x.usd+x.khr/S.rate)]];$("reportPreview").innerHTML=`<div class="report-brand">nona-me coffee</div><div class="report-title">DAILY SALES REPORT</div><p class="muted">${new Date().toLocaleDateString("en-GB")} · ${S.user||"—"}</p>${lines.map((a,i)=>`<div class="report-line ${i===lines.length-1?"report-total":""}"><span>${a[0]}</span><b>${a[1]}</b></div>`).join("")}`}
function exportPng(){const x=summarize(),c=document.createElement("canvas"),ctx=c.getContext("2d");c.width=1000;c.height=1250;ctx.fillStyle="#F8F6F1";ctx.fillRect(0,0,c.width,c.height);ctx.fillStyle="#FFFFFF";ctx.roundRect(60,60,880,1130,28,28);ctx.fill();ctx.fillStyle="#3A2A24";ctx.font="700 44px Arial";ctx.fillText("nona-me coffee",95,135);ctx.fillStyle="#8B2E23";ctx.font="700 30px Arial";ctx.fillText("DAILY SALES REPORT",95,185);ctx.fillStyle="#4B3A32";ctx.font="22px Arial";ctx.fillText("Date: "+new Date().toLocaleDateString("en-GB"),95,230);ctx.fillText("Staff: "+(S.user||"—"),95,265);const rows=[["KHR Sales",moneyKHR(x.khr)],["USD Sales",moneyUSD(x.usd)],["Total Cups",String(x.cups)],["KHR Cash",moneyKHR(x.khrCash)],["KHR ABA",moneyKHR(x.khrAba)],["USD Cash",moneyUSD(x.usdCash)],["USD ABA",moneyUSD(x.usdAba)],["Mixed Total",moneyUSD(x.usd+x.khr/S.rate)],["Rate",Number(S.rate).toLocaleString()+"៛ / $1"]];let y=335;rows.forEach((r,i)=>{if(i===rows.length-1){ctx.strokeStyle="#ddd";ctx.beginPath();ctx.moveTo(95,y-25);ctx.lineTo(905,y-25);ctx.stroke()}ctx.fillStyle=i===rows.length-2?"#8B2E23":"#4B3A32";ctx.font=i===rows.length-2?"700 25px Arial":"22px Arial";ctx.fillText(r[0],95,y);ctx.textAlign="right";ctx.fillText(r[1],905,y);ctx.textAlign="left";y+=75});ctx.fillStyle="#9CA3AF";ctx.font="18px Arial";ctx.fillText("Nona-me Coffee · Daily Sales",95,1125);c.toBlob(blob=>{const a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download=`nona-me-daily-report-${today()}.png`;a.click();URL.revokeObjectURL(a.href)})}
async function copyText(){const txt=reportText();try{await navigator.clipboard.writeText(txt);alert("Report copied / របាយការណ៍ត្រូវបានចម្លង")}catch(e){alert(txt)}}
function downloadTxt(){const blob=new Blob([reportText()],{type:"text/plain;charset=utf-8"}),a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download=`nona-me-daily-report-${today()}.txt`;a.click();URL.revokeObjectURL(a.href)}
async function shareTelegram(){const txt=reportText();if(navigator.share){try{await navigator.share({title:"Nona-me Daily Report",text:txt})}catch(e){}}else{await copyText();window.open("https://t.me/","_blank")}}
function renderHistory(){const list=[...S.sales].reverse().slice(0,100);$("historyList").innerHTML=list.length?list.map(s=>`<div class="history-item"><div><b>${s.date}</b> · ${s.time}<br><small>${s.user} · ${s.payment} · ${s.currency} · ${s.cups} cups</small></div><div class="history-total">${s.currency==="KHR"?moneyKHR(s.amount):moneyUSD(s.amount)}</div></div>`).join(""):'<div class="cart-empty">No sales yet / មិនទាន់មានការលក់</div>'}
boot();