-- Nona-me Sales SaaS Master 2.0
-- Multi-tenant foundation: one business can have many users.
-- Safe to re-run.

create extension if not exists pgcrypto;

create table if not exists public.nona_me_businesses (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  slug text not null unique,
  owner_id uuid not null references auth.users(id) on delete restrict,
  logo_url text,
  settings jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.nona_me_memberships (
  id uuid primary key default gen_random_uuid(),
  business_id uuid not null references public.nona_me_businesses(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  role text not null default 'staff' check (role in ('owner','admin','staff')),
  active boolean not null default true,
  created_at timestamptz not null default now(),
  unique (business_id,user_id)
);

create table if not exists public.nona_me_business_data (
  business_id uuid primary key references public.nona_me_businesses(id) on delete cascade,
  data jsonb not null default '{}'::jsonb,
  updated_by uuid references auth.users(id) on delete set null,
  updated_at timestamptz not null default now()
);

create table if not exists public.nona_me_business_audit (
  id bigint generated by default as identity primary key,
  business_id uuid not null references public.nona_me_businesses(id) on delete cascade,
  user_id uuid references auth.users(id) on delete set null,
  action text not null,
  details jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists nona_me_memberships_user_idx on public.nona_me_memberships(user_id);
create index if not exists nona_me_memberships_business_idx on public.nona_me_memberships(business_id);
create index if not exists nona_me_audit_business_idx on public.nona_me_business_audit(business_id, created_at desc);

create or replace function public.nona_me_is_member(p_business uuid)
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select exists(
    select 1 from public.nona_me_memberships m
    where m.business_id = p_business and m.user_id = auth.uid() and m.active = true
  );
$$;

create or replace function public.nona_me_is_admin(p_business uuid)
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select exists(
    select 1 from public.nona_me_memberships m
    where m.business_id = p_business
      and m.user_id = auth.uid()
      and m.active = true
      and m.role in ('owner','admin')
  );
$$;

create or replace function public.nona_me_create_business(p_name text, p_slug text)
returns public.nona_me_businesses
language plpgsql
security definer
set search_path = ''
as $$
declare
  b public.nona_me_businesses;
begin
  if auth.uid() is null then raise exception 'Not authenticated'; end if;
  if length(trim(coalesce(p_name,''))) < 2 then raise exception 'Business name is required'; end if;
  insert into public.nona_me_businesses(name,slug,owner_id)
  values (trim(p_name), lower(regexp_replace(trim(p_slug), '[^a-zA-Z0-9-]+', '-', 'g')), auth.uid())
  returning * into b;

  insert into public.nona_me_memberships(business_id,user_id,role,active)
  values (b.id,auth.uid(),'owner',true);

  insert into public.nona_me_business_data(business_id,data,updated_by)
  values (b.id, jsonb_build_object(
    'cms', jsonb_build_object('shopName', b.name, 'tagline','Sales Management', 'footer','Thank you'),
    'settings', jsonb_build_object('shopName', b.name, 'rate', 4000),
    'products', '[]'::jsonb,
    'categories', '[]'::jsonb,
    'promotions', '[]'::jsonb,
    'revenueChannels', '[]'::jsonb,
    'expenseCategories', '[]'::jsonb,
    'sales', '[]'::jsonb,
    'expenses', '[]'::jsonb,
    'deposits', '[]'::jsonb,
    'cashCounts', '[]'::jsonb,
    'stock', '[]'::jsonb,
    'users', '[]'::jsonb
  ), auth.uid())
  on conflict (business_id) do nothing;

  return b;
end;
$$;

revoke all on function public.nona_me_create_business(text,text) from public;
grant execute on function public.nona_me_create_business(text,text) to authenticated;

alter table public.nona_me_businesses enable row level security;
alter table public.nona_me_memberships enable row level security;
alter table public.nona_me_business_data enable row level security;
alter table public.nona_me_business_audit enable row level security;

drop policy if exists nona_business_select_member on public.nona_me_businesses;
create policy nona_business_select_member on public.nona_me_businesses
for select to authenticated using (public.nona_me_is_member(id));

drop policy if exists nona_business_update_admin on public.nona_me_businesses;
create policy nona_business_update_admin on public.nona_me_businesses
for update to authenticated using (public.nona_me_is_admin(id)) with check (public.nona_me_is_admin(id));

drop policy if exists nona_membership_select_self on public.nona_me_memberships;
create policy nona_membership_select_self on public.nona_me_memberships
for select to authenticated using (user_id = auth.uid() or public.nona_me_is_admin(business_id));

drop policy if exists nona_membership_admin_modify on public.nona_me_memberships;
create policy nona_membership_admin_modify on public.nona_me_memberships
for all to authenticated using (public.nona_me_is_admin(business_id)) with check (public.nona_me_is_admin(business_id));

drop policy if exists nona_data_member_select on public.nona_me_business_data;
create policy nona_data_member_select on public.nona_me_business_data
for select to authenticated using (public.nona_me_is_member(business_id));

drop policy if exists nona_data_member_insert on public.nona_me_business_data;
create policy nona_data_member_insert on public.nona_me_business_data
for insert to authenticated with check (public.nona_me_is_member(business_id));

drop policy if exists nona_data_member_update on public.nona_me_business_data;
create policy nona_data_member_update on public.nona_me_business_data
for update to authenticated using (public.nona_me_is_member(business_id)) with check (public.nona_me_is_member(business_id));

drop policy if exists nona_audit_member_select on public.nona_me_business_audit;
create policy nona_audit_member_select on public.nona_me_business_audit
for select to authenticated using (public.nona_me_is_member(business_id));

drop policy if exists nona_audit_member_insert on public.nona_me_business_audit;
create policy nona_audit_member_insert on public.nona_me_business_audit
for insert to authenticated with check (public.nona_me_is_member(business_id));

grant usage on schema public to authenticated;
grant select, insert, update on public.nona_me_businesses to authenticated;
grant select, insert, update, delete on public.nona_me_memberships to authenticated;
grant select, insert, update on public.nona_me_business_data to authenticated;
grant select, insert on public.nona_me_business_audit to authenticated;
grant usage, select on all sequences in schema public to authenticated;


-- Staff management: add an existing Supabase Auth account to a business.
-- The staff member should create a Cloud Account first. Admin then adds that email here.
create or replace function public.nona_me_add_member_by_email(p_business uuid, p_email text, p_role text default 'staff')
returns table(user_id uuid, email text, role text)
language plpgsql
security definer
set search_path = ''
as $$
declare
  target_user uuid;
  target_email text;
  chosen_role text;
begin
  if auth.uid() is null then raise exception 'Not authenticated'; end if;
  if not public.nona_me_is_admin(p_business) then raise exception 'Not authorized'; end if;
  chosen_role := case when p_role in ('admin','staff') then p_role else 'staff' end;
  select id, email into target_user, target_email
  from auth.users
  where lower(email) = lower(trim(p_email))
  limit 1;
  if target_user is null then raise exception 'No Cloud Account found for this email. Ask the staff member to create an account first.'; end if;
  insert into public.nona_me_memberships(business_id,user_id,role,active)
  values(p_business,target_user,chosen_role,true)
  on conflict (business_id,user_id) do update
    set role=excluded.role, active=true;
  return query select target_user, target_email, chosen_role;
end;
$$;
revoke all on function public.nona_me_add_member_by_email(uuid,text,text) from public;
grant execute on function public.nona_me_add_member_by_email(uuid,text,text) to authenticated;


-- Master 5.0 role and secure Telegram integration migration.
alter table public.nona_me_memberships drop constraint if exists nona_me_memberships_role_check;
alter table public.nona_me_memberships add constraint nona_me_memberships_role_check check (role in ('owner','admin','manager','staff','cashier','stock_keeper'));

create table if not exists public.nona_me_integrations (
  business_id uuid primary key references public.nona_me_businesses(id) on delete cascade,
  telegram_bot_token text,
  telegram_chat_id text,
  updated_at timestamptz not null default now()
);
alter table public.nona_me_integrations enable row level security;
drop policy if exists nona_integrations_no_client_read on public.nona_me_integrations;
-- No authenticated policies: only server-side service role should read/write secrets.
revoke all on public.nona_me_integrations from anon, authenticated;
grant all on public.nona_me_integrations to service_role;

-- Business data writes are routed through the server-side save API. Members retain read access.
drop policy if exists nona_data_member_update on public.nona_me_business_data;
drop policy if exists nona_data_member_insert on public.nona_me_business_data;
create policy nona_data_admin_insert on public.nona_me_business_data
for insert to authenticated with check (public.nona_me_is_admin(business_id));
create policy nona_data_admin_update on public.nona_me_business_data
for update to authenticated using (public.nona_me_is_admin(business_id)) with check (public.nona_me_is_admin(business_id));
