const SUPABASE_URL = process.env.SUPABASE_URL || 'https://aucwgnbhcbcovmshjmuo.supabase.co';
const SUPABASE_ANON_KEY = process.env.SUPABASE_ANON_KEY || '';
const SERVICE_KEY = process.env.SUPABASE_SERVICE_ROLE_KEY || '';
function json(res,status,body){return res.status(status).setHeader('content-type','application/json; charset=utf-8').setHeader('cache-control','no-store').json(body)}
const clean=v=>String(v??'').trim();
async function rest(path,opts={}){const res=await fetch(`${SUPABASE_URL}${path}`,{...opts,headers:{apikey:SERVICE_KEY,authorization:'Bearer '+SERVICE_KEY,'content-type':'application/json',...(opts.headers||{})}});const raw=await res.text();let data=null;try{data=raw?JSON.parse(raw):null}catch{}return {res,data,raw}}
async function authUser(token){const r=await fetch(`${SUPABASE_URL}/auth/v1/user`,{headers:{apikey:SERVICE_KEY,authorization:'Bearer '+token}});const d=await r.json().catch(()=>null);return r.ok?d:null}
async function requireAdmin(token,businessId){const u=await authUser(token);if(!u?.id)return null;const m=await rest(`/rest/v1/nona_me_memberships?business_id=eq.${encodeURIComponent(businessId)}&user_id=eq.${encodeURIComponent(u.id)}&active=eq.true&select=role`);if(!m.res.ok||!m.data?.length||!['owner','admin'].includes(m.data[0].role))return null;return u}
function validUsername(x){return /^[a-z0-9._-]{3,32}$/.test(x)}
export default async function handler(req,res){if(req.method!=='POST')return json(res,405,{ok:false,error:'Use POST.'});if(!SERVICE_KEY)return json(res,500,{ok:false,error:'SUPABASE_SERVICE_ROLE_KEY is not configured.'});try{const token=clean(req.headers.authorization||'').replace(/^Bearer\s+/i,'');const body=typeof req.body==='string'?JSON.parse(req.body):req.body||{};const businessId=clean(body.businessId);if(!businessId||!await requireAdmin(token,businessId))return json(res,403,{ok:false,error:'Not authorized.'});const action=clean(body.action)||'create';
if(action==='create'){const username=clean(body.username).toLowerCase();const name=clean(body.name),password=String(body.password||'');const role=['admin','manager','staff','cashier','stock_keeper'].includes(body.role)?body.role:'staff';const shift=body.shift==='day'?'day':'morning';if(!validUsername(username))return json(res,400,{ok:false,error:'Username must be 3-32 characters: letters, numbers, dot, dash or underscore.'});if(password.length<6)return json(res,400,{ok:false,error:'Password must be at least 6 characters.'});const email=username+'@users.nona-me.local';const created=await rest('/auth/v1/admin/users',{method:'POST',headers:{'authorization':'Bearer '+SERVICE_KEY,'apikey':SERVICE_KEY},body:JSON.stringify({email,password,email_confirm:true,user_metadata:{display_name:name,username,created_by:'admin'}})});if(!created.res.ok)return json(res,400,{ok:false,error:created.data?.msg||created.data?.message||created.raw||'Could not create staff account.'});const uid=created.data?.user?.id||created.data?.id;if(!uid)return json(res,500,{ok:false,error:'Staff user id was not returned.'});const mem=await rest('/rest/v1/nona_me_memberships',{method:'POST',headers:{prefer:'resolution=merge-duplicates'},body:JSON.stringify({business_id:businessId,user_id:uid,role,active:true})});if(!mem.res.ok)return json(res,500,{ok:false,error:mem.raw||'Could not create membership.'});return json(res,200,{ok:true,user_id:uid,username,role,shift,email})}
if(action==='reset-password'){const userId=clean(body.userId),password=String(body.password||'');if(!userId||password.length<6)return json(res,400,{ok:false,error:'User id and password are required.'});const r=await fetch(`${SUPABASE_URL}/auth/v1/admin/users/${encodeURIComponent(userId)}`,{method:'PUT',headers:{authorization:'Bearer '+SERVICE_KEY,apikey:SERVICE_KEY,'content-type':'application/json'},body:JSON.stringify({password})});const d=await r.json().catch(()=>null);if(!r.ok)return json(res,400,{ok:false,error:d?.message||d?.msg||'Could not reset password.'});return json(res,200,{ok:true})}
if(action==='set-active'){const userId=clean(body.userId),active=Boolean(body.active);const r=await rest(`/rest/v1/nona_me_memberships?business_id=eq.${encodeURIComponent(businessId)}&user_id=eq.${encodeURIComponent(userId)}`,{method:'PATCH',body:JSON.stringify({active})});if(!r.res.ok)return json(res,400,{ok:false,error:r.raw||'Could not update account.'});return json(res,200,{ok:true,active})}
return json(res,400,{ok:false,error:'Unknown action.'})}catch(e){return json(res,500,{ok:false,error:e?.message||String(e)})}}
