const TELEGRAM_API='https://api.telegram.org/bot';
const SUPABASE_URL=process.env.SUPABASE_URL||'https://aucwgnbhcbcovmshjmuo.supabase.co';
const SUPABASE_ANON_KEY=process.env.SUPABASE_ANON_KEY||'sb_publishable_XKT_TSLgOd75bhapXEUZ2Q_rs98dwcO';
const SERVICE_KEY=process.env.SUPABASE_SERVICE_ROLE_KEY||'';
const clean=v=>String(v??'').replace(/\r\n/g,'\n').trim();
function json(res,status,body){return res.status(status).setHeader('content-type','application/json; charset=utf-8').setHeader('cache-control','no-store').json(body)}
async function rest(path,opts={}){if(!SERVICE_KEY)throw new Error('SUPABASE_SERVICE_ROLE_KEY is not configured.');const r=await fetch(`${SUPABASE_URL}${path}`,{...opts,headers:{apikey:SERVICE_KEY,authorization:'Bearer '+SERVICE_KEY,'content-type':'application/json',...(opts.headers||{})}});const raw=await r.text();let data=null;try{data=raw?JSON.parse(raw):null}catch{}return {response:r,raw,data}}
async function authUser(accessToken){if(!accessToken)return null;const r=await fetch(`${SUPABASE_URL}/auth/v1/user`,{headers:{apikey:SUPABASE_ANON_KEY,authorization:'Bearer '+accessToken}});const d=await r.json().catch(()=>null);return r.ok?d:null}
async function getConfig(businessId,accessToken){const user=await authUser(accessToken);if(!user?.id)return {ok:false,status:401,error:'Invalid session.'};const mem=await rest(`/rest/v1/nona_me_memberships?business_id=eq.${encodeURIComponent(businessId)}&user_id=eq.${encodeURIComponent(user.id)}&active=eq.true&select=role`);if(!mem.response.ok||!mem.data?.length)return {ok:false,status:403,error:'Not authorized for this business.'};const row=await rest(`/rest/v1/nona_me_integrations?business_id=eq.${encodeURIComponent(businessId)}&select=telegram_bot_token,telegram_chat_id`);const rec=row.data?.[0]||{};const botToken=clean(rec.telegram_bot_token)||clean(process.env.TELEGRAM_BOT_TOKEN);const chatId=clean(rec.telegram_chat_id);return {ok:true,user,role:mem.data[0].role,botToken,chatId}}
function telegramError(data,fallback){const description=data?.description||fallback||'Telegram API failed.';const code=data?.error_code?` [${data.error_code}]`:'';return `${description}${code}`}
async function telegramCall(botToken,method,body){return fetch(`${TELEGRAM_API}${botToken}/${method}`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(body)})}
function multipart(fields,fileBuffer,fileType='image/png',uploadName='nona-me-daily-report.png',fieldName='document'){const boundary='----NonaMeTelegram'+Math.random().toString(16).slice(2);const chunks=[];const push=x=>chunks.push(Buffer.isBuffer(x)?x:Buffer.from(x));const line=`--${boundary}\r\n`;for(const [name,value] of Object.entries(fields)){if(value===undefined||value===null||value==='')continue;push(line);push(`Content-Disposition: form-data; name="${name}"\r\n\r\n`);push(String(value)+'\r\n')}push(line);push(`Content-Disposition: form-data; name="${fieldName}"; filename="${uploadName}"\r\n`);push(`Content-Type: ${fileType}\r\n\r\n`);push(fileBuffer);push('\r\n');push(`--${boundary}--\r\n`);const body=Buffer.concat(chunks);return {headers:{'content-type':`multipart/form-data; boundary=${boundary}`,'content-length':String(body.length)},body}}
async function parseReq(req){return typeof req.body==='string'?JSON.parse(req.body):req.body||{}}
export default async function handler(req,res){const route=clean(req.query?.route).toLowerCase();try{if(route==='health'||(!route&&req.method==='GET')){if(req.method!=='GET')return json(res,405,{ok:false,error:'Use GET.'});const access=clean(req.headers.authorization||'').replace(/^Bearer\s+/i,'');const businessId=clean(req.query?.businessId);let cfg;if(businessId)cfg=await getConfig(businessId,access);else cfg={ok:true,botToken:clean(process.env.TELEGRAM_BOT_TOKEN),chatId:''};if(!cfg.ok)return json(res,cfg.status,cfg);if(!cfg.botToken)return json(res,500,{ok:false,error:'Telegram Bot Token is not configured.'});const r=await telegramCall(cfg.botToken,'getMe',{}),raw=await r.text();let d=null;try{d=JSON.parse(raw)}catch{};if(!r.ok||!d?.ok)return json(res,502,{ok:false,error:telegramError(d,raw)});return json(res,200,{ok:true,bot:d.result?.username||null})}
if(route==='test'){if(req.method!=='POST')return json(res,405,{ok:false,error:'Use POST.'});const body=await parseReq(req);const cfg=body.businessId?await getConfig(clean(body.businessId),clean(body.accessToken||req.headers.authorization||'').replace(/^Bearer\s+/i,'')):{ok:true,botToken:clean(process.env.TELEGRAM_BOT_TOKEN),chatId:clean(body.chatId)};if(!cfg.ok)return json(res,cfg.status,cfg);const chatId=clean(body.chatId)||cfg.chatId;if(!cfg.botToken||!chatId)return json(res,400,{ok:false,error:'Bot Token and Group / Channel ID are required.'});const me=await telegramCall(cfg.botToken,'getMe',{}),md=await me.json().catch(()=>null);if(!me.ok||!md?.ok)return json(res,502,{ok:false,error:telegramError(md,'Invalid Telegram Bot Token.')});const tx=await telegramCall(cfg.botToken,'sendMessage',{chat_id:chatId,text:'Nona-me Telegram connection test\nBot: @'+(md.result?.username||'bot')});const td=await tx.json().catch(()=>null);if(!tx.ok||!td?.ok)return json(res,502,{ok:false,error:telegramError(td,'Telegram could not send the test message.')});return json(res,200,{ok:true,message_id:td.result?.message_id||null})}
if(route==='send'||route==='report'){if(req.method!=='POST')return json(res,405,{ok:false,error:'Use POST.'});const body=await parseReq(req);const cfg=await getConfig(clean(body.businessId),clean(body.accessToken||req.headers.authorization||'').replace(/^Bearer\s+/i,''));if(!cfg.ok)return json(res,cfg.status,cfg);const chatId=clean(cfg.chatId)||clean(body.chatId);if(!cfg.botToken||!chatId)return json(res,400,{ok:false,error:'Telegram Bot Token and Group / Channel ID are required.'});if(!body.image)return json(res,400,{ok:false,error:'Daily report image is required.'});const match=/^data:image\/(jpeg|jpg|png);base64,(.+)$/i.exec(String(body.image));if(!match)return json(res,400,{ok:false,error:'Invalid report image.'});const buf=Buffer.from(match[2],'base64');if(!buf.length)return json(res,400,{ok:false,error:'The report image is empty.'});if(buf.length>9_500_000)return json(res,413,{ok:false,error:'Report image is too large. Lower the report resolution.'});const rawCaption=clean(body.caption);const caption=(rawCaption||'Nona-me Coffee — Daily Sales Report').slice(0,1024);const type=/^data:image\/png/i.test(String(body.image))?'image/png':'image/jpeg';const method=body.delivery==='photo'?'sendPhoto':'sendDocument';const field=body.delivery==='photo'?'photo':'document';const fileName=type==='image/png'?'nona-me-daily-report.png':'nona-me-daily-report.jpg';const mp=multipart({chat_id:chatId,caption},buf,type,fileName,field);const tx=await fetch(`${TELEGRAM_API}${cfg.botToken}/${method}`,{method:'POST',headers:mp.headers,body:mp.body});const raw=await tx.text();let d=null;try{d=raw?JSON.parse(raw):null}catch{};if(!tx.ok||!d?.ok)return json(res,502,{ok:false,error:telegramError(d,raw)});return json(res,200,{ok:true,delivery:body.delivery==='photo'?'photo':'document',message_id:d.result?.message_id||null})}
return json(res,404,{ok:false,error:'Unknown Telegram route.'})}catch(e){return json(res,500,{ok:false,error:e?.message||String(e)})}}
export const config={api:{bodyParser:{sizeLimit:'10mb'}}};
